---
- name: stop and remove docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ growthbook_compose_path }}"
    state: absent
    remove_orphans: true

- name: remove growthbook directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ growthbook_compose_path }}"
    - "{{ growthbook_base_path }}"

