---
- name: Copy compose-file - loki
  ansible.builtin.template:
    src: "docker-compose.loki.yml.j2"
    dest: "{{ loki_compose_path }}/docker-compose.yml"
    mode: "0600"
  notify: recreate-docker loki
