{
 "title": "Clickhouse flant exporter",
 "description": "Clickhouse metrics",
 "tags": [
  "clickhouse",
  "db",
  "flant"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stand",
    "label": "stand",
    "query": {
     "query": "label_values({job=~\"clickhouse.*.exporter\"},stand)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=~\"clickhouse.*.exporter\",stand=~\"$stand\"},instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection{instance=~\"$instance\"}",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "clickhouse_http_connection{instance=~\"$instance\"}",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "clickhouse_interserver_connection{instance=~\"$instance\"}",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_merge{instance=~\"$instance\"}",
     "legendFormat": "merge {{job}}"
    },
    {
     "expr": "rate(clickhouse_merged_rows_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(clickhouse_query_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Query total 1 second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Query insert/select 1 second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_insert_query_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "insert - {{instance}}"
    },
    {
     "expr": "rate(clickhouse_select_query_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "select - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_memory_tracking{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task{instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_leader_replica{instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_replicated_checks{instance=~\"$instance\"}"
    },
    {
     "expr": "clickhouse_replicated_fetch{instance=~\"$instance\"}"
    },
    {
     "expr": "clickhouse_replicated_send{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clickhouse_readonly_replica{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_read{instance=~\"$instance\"}"
    },
    {
     "expr": "clickhouse_write{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_mark_cache_misses_total{instance=~\"$instance\"}",
     "legendFormat": "misses {{job}}"
    },
    {
     "expr": "clickhouse_mark_cache_hits_total{instance=~\"$instance\"}",
     "legendFormat": "hits {{job}}"
    }
   ]
  }
 ]
}