---
- name: Debug node labels
  ansible.builtin.debug:
    msg: "Node labels for {{ ansible_hostname }}: {{ k8s_node_labels_manual }}"

- name: Label this node according to manual configuration
  ansible.builtin.shell: |
    {% for label in k8s_node_labels_manual %}
    kubectl --kubeconfig {{ k8s_config_path }} label node {{ ansible_hostname }} {{ label.name }}={{ label.value }} --overwrite
    {% endfor %}
  when: k8s_node_labels_manual is defined and k8s_node_labels_manual | length > 0
  delegate_to: "{{ k8s_master_init_host }}"

- name: Ensure node labels are applied
  ansible.builtin.command: >
    kubectl --kubeconfig {{ k8s_config_path }} get node {{ ansible_hostname }} --show-labels
  when: k8s_node_labels_manual is defined and k8s_node_labels_manual | length > 0
  delegate_to: "{{ k8s_master_init_host }}"
