---
rate_hub_api_image: "denisitpro/rate-api"
rate_hub_collector_image: "denisitpro/rate-collector"
rate_hub_version: "latest"
rate_hub_api_version: "{{ rate_hub_version }}"
rate_hub_collector_version: "{{ rate_hub_version }}"

rate_hub_uid: 1006
rate_hub_gid: 1006

rate_hub_compose_path: "/opt/docker/rate-hub"
rate_hub_base_path: "/opt/rate-hub"
