---
- name: copy compose file
  ansible.builtin.template:
    src: "docker-compose.rate-hub.yml.j2"
    dest: "{{ rate_hub_compose_path }}/docker-compose.yml"
    mode: "0600"
  notify: restart-docker rate-hub

- name: copy env-file - rate-api
  ansible.builtin.template:
    src: "rate-api.remote.env.j2"
    dest: "{{ rate_hub_compose_path }}/rate-api.remote.env"
    mode: "0600"
  notify: restart-docker rate-hub

- name: copy env-file - rate-collector
  ansible.builtin.template:
    src: "rate-collector.remote.env.j2"
    dest: "{{ rate_hub_compose_path }}/rate-collector.remote.env"
    mode: "0600"
  notify: restart-docker rate-hub

- name: copy env-file - rate-api-x402
  ansible.builtin.template:
    src: "rate-api-x402.remote.env.j2"
    dest: "{{ rate_hub_compose_path }}/rate-api-x402.remote.env"
    mode: "0600"
  when: rate_hub_x402_enabled
  notify: restart-docker rate-hub

- name: Ensure docker-compose is applied and containers are recreated if needed
  community.docker.docker_compose_v2:
    project_src: "{{ rate_hub_compose_path }}"
    state: present
    recreate: always
    pull: always
