---
- name: copy compose file - outline
  ansible.builtin.template:
    src: "docker-compose.outline.yml.j2"
    dest: "{{ outline_compose_path }}/docker-compose.yml"
    mode: "0640"
  notify: recreate-docker outline