---
- ansible.builtin.import_tasks: 05-path.yml
  tags:
    - outline
    - outline-prefly

- ansible.builtin.import_tasks: 50-compose.yml
  tags:
    - outline
    - outline-compose

- ansible.builtin.import_tasks: 99-clean.yml
  tags: ['never', 'outline-clean']
