---
- ansible.builtin.import_tasks: 05-path.yml
  tags:
    - es
    - es-prefly

- ansible.builtin.import_tasks: 10-config.yml
  tags:
    - es
    - es-config

- ansible.builtin.import_tasks: 50-compose.yml
  tags:
    - es
    - es-compose
