---
- ansible.builtin.import_tasks: 05-prefly.yml
  tags:
    - redis
    - redis-prefly

- ansible.builtin.import_tasks: 10-configure.yml
  tags:
    - redis
    - redis-config

# - ansible.builtin.import_tasks: 50-consul-reg.yml
#   when: consul_monitoring_disable is not defined
#   tags:
#     - consul
#     - redis
#     - consul-reg

- ansible.builtin.import_tasks: 90-restart.yml
  tags: ['never', 'redis-restart']
