---
- name: create docker folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: root
    group: root
  with_items:
    - "/opt/docker"

- name: create folder application
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - "{{ oauth2_proxy_compose_path }}"
