---
- name: stop compose
  community.docker.docker_compose_v2:
    project_src: "{{ oauth2_proxy_compose_path }}"
    state: stopped
  register: compose_result
  failed_when:
    - compose_result is failed
    - "'No such container' not in compose_result.msg"
  tags:
    - never
    - oauth2-proxy-stop

- name: start compose
  community.docker.docker_compose_v2:
    project_src: "{{ oauth2_proxy_compose_path }}"
    state: present
  tags:
    - never
    - oauth2-proxy-start
