---
- name: === Update apt repo and cache ===
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: === Upgrade all apt packages ===
  apt: upgrade=dist force_apt_get=yes

- name: === Check if a reboot is needed for Debian and Ubuntu boxes ===
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_checksum=false

- name: === apt install multiple packages ===
  register: updatesys
  apt:
    update_cache: yes
    name: "{{ install_packages_list }}"
    state: present

- name: === Remove useless packages from the cache ===
  apt:
    autoclean: yes

- name: === Remove dependencies that are no longer required ===
  apt:
    autoremove: yes

#- name: === start qemu-guest-agent ===
#  systemd:
#    name: qemu-guest-agent
#    state: started
#    enabled: yes
#  ignore_errors: true

- name: === Config sshd ===
  copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config
    mode: 0644

- name: === Restart SSH ===
  service:
    name: ssh
    state: restarted

- name: === Remove unattended-upgrades ===
  apt:
    name: unattended-upgrades
    state: absent

- name: === Reboot the server ===
  reboot:
      msg: "Reboot initiated by Ansible due to kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
  when: reboot_required_file.stat.exists