---
- ansible.builtin.import_tasks: 05-prefly.yml
  tags:
    - loki-dumps
    - loki-dumps-prefly

- ansible.builtin.import_tasks: 10-logcli.yml
  tags:
    - loki-dumps
    - loki-dumps-logcli

- ansible.builtin.import_tasks: 15-files.yml
  tags:
    - loki-dumps
    - loki-dumps-files