---
- name: Deploy kubelet resolv.conf template
  ansible.builtin.template:
    src: "shared/templates/kubelet/kubelet.resolv.conf.j2"
    dest: "{{ kubelet_resolv_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart kubelet

- name: copy kubelet.yml override config
  ansible.builtin.template:
    src: "shared/templates/kubelet/kubelet-config.yaml.j2"
    dest: /var/lib/kubelet/config.yaml
    owner: root
    group: root
    mode: "0644"
  notify: restart kubelet
