---
ssl_selfsign_type: "rsa"
nginx_logs_disabled: true

upstream_multi:
  upstream:
    - {name: "backend", server: "127.0.0.1", port: 3000, fail_timeout: 30, max_fails: 30, conf: "nginx-multi-g3.conf.j2", keepalive: 32}

nginx_access_log_format: extend_json
# nginx_error_log_format: warn
angie_mtls_support: true
nginx_logs_stdout: true

nginx:
  vhosts:
    - servername: "api.tips-flow.com"
      domain: "selfsign"
      config_file: "angie2-general-g4.conf.j2"
      upstream_protocol: http
      upstream_name: "backend"
      client_max_body_size: 50M
