---
infisical_project_id: "3195d55d-4423-4e4f-b74c-4d6c03f56aec"
infisical_environment: "dev"

infisical_extend_g1:
  - name: tg_notify_bot_token
    secret_path: "/"
    secret_name: "TELEGRAM_BOT_TOKEN"
  - name: tg_notify_bot_chat_id
    secret_path: "/"
    secret_name: "KORA_NOTIFY_BOT_TELEGRAM_CHAT_ID"
  - name: kora_rpc_url_devnet
    secret_path: "/"
    secret_name: "KORA_RPC_URL_DEVNET"
  - name: kora_rpc_url_mainnet
    secret_path: "/"
    secret_name: "KORA_RPC_URL_MAINNET"
  - name: kora_jupiter_api_key
    secret_path: "/"
    secret_name: "KORA_JUPITER_API_KEY"
  - name: rate_hub_coingecko_api_key
    secret_path: "/"
    secret_name: "COINGECKO_API_KEY"
  - name: rate_hub_api_keys
    secret_path: "/"
    secret_name: "RATE_HUB_API_KEYS"

#### Sigma Tracker API secrets
  - name: tracker_api_database_url
    project_id: "9f303575-7a4d-4d7e-ac90-7a72cda2c7f1"  # sigma-tracker
    environment: "prod"
    secret_path: "/"
    secret_name: "SIGMA_TRACKER_API_DATABASE_URL"
  - name: tracker_api_apns_key_id
    project_id: "9f303575-7a4d-4d7e-ac90-7a72cda2c7f1"  # sigma-tracker
    environment: "prod"
    secret_path: "/"
    secret_name: "SIGMA_TRACKER_API_APNS_KEY_ID"
  - name: tracker_api_apns_p8
    project_id: "9f303575-7a4d-4d7e-ac90-7a72cda2c7f1"  # sigma-tracker
    environment: "prod"
    secret_path: "/"
    secret_name: "SIGMA_TRACKER_API_APNS_P8"
  - name: tracker_api_apns_team_id
    project_id: "9f303575-7a4d-4d7e-ac90-7a72cda2c7f1"  # sigma-tracker
    environment: "prod"
    secret_path: "/"
    secret_name: "APNS_TEAM_ID"
  - name: tracker_api_rate_hub_api_key
    project_id: "9f303575-7a4d-4d7e-ac90-7a72cda2c7f1"  # sigma-tracker
    environment: "prod"
    secret_path: "/"
    secret_name: "SIGMA_TRACKER_API_RATE_HUB_API_KEY"
  - name: tracker_api_admin_token
    project_id: "9f303575-7a4d-4d7e-ac90-7a72cda2c7f1"  # sigma-tracker
    environment: "prod"
    secret_path: "/"
    secret_name: "SIGMA_TRACKER_API_ADMIN_TOKEN"
