---
rate_hub_api_http_addr: "127.0.0.1:18080"
# Put COINGECKO_API_KEY at secret path / in the g1 Infisical project before deploying.
rate_hub_coingecko_api_key: "{{ infisical_dict_users_secret_g1.rate_hub_coingecko_api_key }}"
# Put RATE_HUB_API_KEYS at secret path / in the g1 Infisical project before deploying.
rate_hub_api_keys: "{{ infisical_dict_users_secret_g1.rate_hub_api_keys }}"

rate_hub_version: "0.6.0"