---
tg_notify_bot_instances:
  - name: tg-notify-kora-devnet
    tg_notify_bot_token: "{{ infisical_dict_users_secret_g1.tg_notify_bot_token }}"
    tg_notify_bot_chat_id: "{{ infisical_dict_users_secret_g1.tg_notify_bot_chat_id }}"
    tg_notify_bot_env:
      WATCH_DEVNET_TREASURY_ADDRESS: "FqqJ9aAgwGQBosT8Re3wdqqKVR7aTEvHez5P58MyvXrF"
      WATCH_DEVNET_FEE_USDC_ADDRESS: "3Sfkkg8jD1otcwcoJGHy5SjzHbBr3u9QjQB84AZNt5rr"
