iptables_rule_g2:
  ipv4:
    - { name: "ssh", protocol: "tcp", port: "22" }
    - { name: "http", protocol: "tcp", port: "80" }
    - { name: "https", protocol: "tcp", port: "443" }
  ipv6:
    - { name: "ssh", protocol: "tcp", port: "22" }
    - { name: "http", protocol: "tcp", port: "80" }
    - { name: "https", protocol: "tcp", port: "443" }
