{
 "title": "FreeTon Relay Dashboard - provision",
 "description": "FreeTon Validator Dashboard",
 "tags": [
  "Ton",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values({job=\"everscale_metrics\"}, job) "
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"everscale_metrics\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last processed EVM block",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "eth_subscriber_last_processed_block{}"
    }
   ]
  },
  {
   "title": "Staker Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "staking_user_data_tokens_balance{}/1000000000"
    }
   ]
  },
  {
   "title": "Shard time diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ton_subscriber_shard_client_time_diff{}"
    }
   ]
  },
  {
   "title": "Node DIff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ton_subscriber_time_diff{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "TON Ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ton_subscriber_ready{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Elections Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "staking_elections_status{}" }
   ]
  },
  {
   "title": "TON Current time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ton_subscriber_current_utime{}*1000"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "RAM used "
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=~\"$job\"} / node_memory_SwapTotal_bytes{job=~\"$job\"})) * 100",
     "legendFormat": "SWAP used "
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk used"
    }
   ]
  },
  {
   "title": "SOL unrecognized proposals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sol_subscriber_unrecognized_proposals_count{}"
    }
   ]
  },
  {
   "title": "ton_subscriber_time_diff",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ton_subscriber_time_diff{job=\"$job\"}",
     "legendFormat": "aggregated per min"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job='$job',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job='$job',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "IPv4 UDP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "events" }
   ],
   "targets": [
    {
     "expr": "netdata_ipv4_udperrors_events_persec_average",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}_{{device}}_Writes completed"
    }
   ]
  }
 ]
}