---
- name: copy compose-file - gitlab
  ansible.builtin.template:
    src: "docker-compose.gitlab.yml.j2"
    dest: "{{ gitlab_docker_compose_path }}/docker-compose.yml"
    mode: '0600'
    owner: root
    group: root
  notify: recreate-docker gitlab
