---
- name: create folder gitlab
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ gitlab_conf_path }}/ssl"

