---
- ansible.builtin.import_tasks: 05-prefly.yml
  tags:
    - gitlab

- ansible.builtin.import_tasks: 10-configure.yml
  tags:
    - gitlab
    - gitlab-compose

- ansible.builtin.import_tasks: 15-copy-ssl.yml
  when: gitlab_support_ssl is defined
  tags:
    - gitlab
    - gitlab-ssl

- ansible.builtin.import_tasks: 85-backup-cron.yml
  when: gitlab_backup_enabled | default(false)
  tags:
    - gitlab
    - gitlab-backup
    - gitlab-backup-cron

- ansible.builtin.import_tasks: 90-clean.yml
  tags: ['never', 'gitlab-clean']