---
elasticsearch_exporter_version: "v1.10.0"
elasticsearch_exporter_compose_path: /opt/docker/elasticsearch-exporter
elasticsearch_exporter_uri: "http://localhost:9200"
elasticsearch_exporter_bind_port: "9114"

# Consul registration
consul_elasticsearch_exporter_enabled: true
consul_elasticsearch_exporter_name: "elasticsearch-exporter"
consul_elasticsearch_exporter_tags:
  - "prometheus"
  - "exporter=elasticsearch-exporter"
  - "stand={{ stand_type | default('undefined') }}"
  - "dc={{ consul_dc_name | default('undefined') }}"
consul_elasticsearch_exporter_token: "{{ vault_dict_users_secret_g2.consul_all_exporters_token.value | default(omit) }}"
consul_install_mode: "docker"
consul_compose_path: /opt/docker/consul
