---
- name: ensure /root/.kube exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: copy kubeconfig for root
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: '0600'
