---
- name: copy compose file
  ansible.builtin.template:
    src: "docker-compose.opensearch-exporter.yml.j2"
    dest: "{{ opensearch_exporter_compose_path }}/docker-compose.yml"
    mode: "0600"
  notify: recreate-docker opensearch-exporter
