---
- name: Stop and remove opensearch-exporter container
  community.docker.docker_compose_v2:
    project_src: "{{ opensearch_exporter_compose_path }}"
    state: absent
  failed_when: false

- name: Remove compose directory
  ansible.builtin.file:
    path: "{{ opensearch_exporter_compose_path }}"
    state: absent

- name: Remove Consul service definition
  ansible.builtin.file:
    path: /etc/consul.d/opensearch-exporter.hcl
    state: absent
  notify: reload consul
  when: consul_opensearch_exporter_enabled | default(true) | bool
