- name: restart consul
  when: consul_install_mode == "unit"
  ansible.builtin.systemd_service:
    name: consul
    state: restarted

- name: reload consul
  when: consul_install_mode == "unit"
  ansible.builtin.systemd_service:
    name: consul
    state: reloaded

- name: restart-docker consul
  when: consul_install_mode == "docker"
  community.docker.docker_compose_v2:
    project_src: "{{ consul_compose_path }}"
    state: restarted

- name: restart-docker consul-compose
  when: consul_install_mode == "docker"
  community.docker.docker_compose_v2:
    project_src: "{{ consul_compose_path }}"
    state: restarted

- name: recreate-docker consul-compose
  when: consul_install_mode == "docker"
  community.docker.docker_compose_v2:
    project_src: "{{ consul_compose_path }}"
    state: present
    recreate: always
    pull: always
