---
- name: recreate-docker redis
  community.docker.docker_compose_v2:
    project_src: "{{ redis_compose_path }}"
    state: present
    recreate: always
    pull: always

- name: restart redis
  community.docker.docker_compose_v2:
    project_src: "{{ redis_compose_path }}"
    state: restarted
