---
- ansible.builtin.import_tasks: 10-nofiles.yml
  tags:
    - ulimits
    - tune

- ansible.builtin.import_tasks: 15-inotify.yml
  when: inotify_tune is defined
  tags:
    - tune
    - inotify
    - ulimits

- ansible.builtin.import_tasks: 20-docker-ulimits.yml
  when: k6_load_test | default(false) | bool
  tags:
    - tune
    - ulimits
    - docker
    - k6-load-test
