{
 "title": "process-exporter v1",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs,job)"
    }
   },
   {
    "name": "Instance",
    "label": "instance",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs{job=\"$job\"},instance)"
    }
   },
   {
    "name": "process",
    "label": "process",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs{job=\"$job\", instance=\"$Instance\"},groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "validator - cpu load % ${process}",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"${process}\", instance=\"${Instance}\"}[5m])) by (instance) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator memory  usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(namedprocess_namegroup_memory_bytes{groupname=\"${process}\", memtype=\"resident\", instance=\"$Instance\"}+namedprocess_namegroup_memory_bytes{groupname=\"${process}\",instance=\"$Instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "process count - ${Instance}",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{job=\"${job}\", instance=\"${Instance}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime - ${Instance}",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (avg by (groupname) (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$Instance\"} > 0))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}