---
- name: Download sql-exporter binary
  unarchive:
    src: "{{ sql_exporter_download_url }}"
    dest: "/tmp"
    remote_src: yes
  register: download_archive

- name: Move sql-exporter binary to install directory
  copy:
    src: "/tmp/sql_exporter-{{ sql_exporter_version }}.linux-{{ sql_exporter_arch }}/sql_exporter"
    dest: "{{ sql_exporter_binary_install_dir }}/sql_exporter"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  notify: restart sql-exporter
  when: download_archive.changed
