---
- ansible.builtin.import_tasks: 05-path.yml
  tags:
    - mailpit
    - mailpit-prefly

- ansible.builtin.import_tasks: 50-compose.yml
  tags:
    - mailpit
    - mailpit-compose

- ansible.builtin.import_tasks: 99-clean.yml
  tags: ['never', 'mailpit-clean']
